### PR TITLE
Prefer switch/case when it compiles to a "tableswitch"

### PR DESCRIPTION
**Pull request by nremond**
Hi,

Can I ask you where your JMH script is? 
Just curious to see what impact this has.

Regards

### CODE REVIEW

**Comment by brettwooldridge** [comment]
The JVM does not trigger a tableswitch until 17 cases are reached, otherwise a cascading comparison is performed.

**Comment by nremond** [comment]
I didn't know about that ...

I did a quick test with this file https://gist.github.com/nremond/37c023c1ecf30840a901d6ee7fef70f5

`javac TestSwitch.java` and then, `javap -c TestSwitch.class`  gives me:

```
  public void tellItLikeItIs();
    Code:
       0: getstatic     #3                  // Field TestSwitch$1.$SwitchMap$TestSwitch$Day:[I
       3: aload_0
       4: getfield      #2                  // Field day:LTestSwitch$Day;
       7: invokevirtual #4                  // Method TestSwitch$Day.ordinal:()I
      10: iaload
      11: tableswitch   { // 1 to 4
                     1: 40
                     2: 51
                     3: 62
                     4: 62
               default: 73
          }
      40: getstatic     #5                  // Field java/lang/System.out:Ljava/io/PrintStream;
      43: ldc           #6                  // String Mondays are bad.
      45: invokevirtual #7                  // Method java/io/PrintStream.println:(Ljava/lang/String;)V
      48: goto          81
```

What am I missing?

Thank you

**Comment by brettwooldridge** [comment]
What version of Java?  And can you try it with strings?

**Comment by nremond** [comment]
I'm testing with Java 1.8.0_121

Here is the same kind of test but based on strings: https://gist.github.com/nremond/9844d349fb7a4903f2fbb05f01c4056b

I get the following bytecode:

```
public void tellItLikeItIs();
    Code:
       0: aload_0
       1: getfield      #2                  // Field day:Ljava/lang/String;
       4: astore_1
       5: iconst_m1
       6: istore_2
       7: aload_1
       8: invokevirtual #3                  // Method java/lang/String.hashCode:()I
      11: lookupswitch  { // 4
           -2015173360: 52
           -1837857328: 94
           -1331574855: 80
            2082011487: 66
               default: 105
          }
      52: aload_1
      53: ldc           #4                  // String MONDAY
      55: invokevirtual #5                  // Method java/lang/String.equals:(Ljava/lang/Object;)Z
      58: ifeq          105
      61: iconst_0
      62: istore_2
      63: goto          105
      66: aload_1
      67: ldc           #6                  // String FRIDAY
      69: invokevirtual #5                  // Method java/lang/String.equals:(Ljava/lang/Object;)Z
      72: ifeq          105
      75: iconst_1
      76: istore_2
      77: goto          105
      80: aload_1
      81: ldc           #7                  // String SATURDAY
      83: invokevirtual #5                  // Method java/lang/String.equals:(Ljava/lang/Object;)Z
      86: ifeq          105
      89: iconst_2
      90: istore_2
      91: goto          105
      94: aload_1
      95: ldc           #8                  // String SUNDAY
      97: invokevirtual #5                  // Method java/lang/String.equals:(Ljava/lang/Object;)Z
     100: ifeq          105
     103: iconst_3
     104: istore_2
     105: iload_2
     106: tableswitch   { // 0 to 3
                     0: 136
                     1: 147
                     2: 158
                     3: 158
               default: 169
          }
     136: getstatic     #9                  // Field java/lang/System.out:Ljava/io/PrintStream;
     139: ldc           #10                 // String Mondays are bad.
     141: invokevirtual #11                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
     144: goto          177
     147: getstatic     #9                  // Field java/lang/System.out:Ljava/io/PrintStream;
     150: ldc           #12                 // String Fridays are better.
     152: invokevirtual #11                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
     155: goto          177
     158: getstatic     #9                  // Field java/lang/System.out:Ljava/io/PrintStream;
     161: ldc           #13                 // String Weekends are best.
     163: invokevirtual #11                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
     166: goto          177
     169: getstatic     #9                  // Field java/lang/System.out:Ljava/io/PrintStream;
     172: ldc           #14                 // String Midweek days are so-so.
     174: invokevirtual #11                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
     177: return
```

**Comment by brettwooldridge** [comment]
Cool.  Can you try it with the benchmark?

**Comment by nremond** [comment]
Based on your benchmark, that's what I get on my machine:

```
Before

Benchmark                    Mode  Cnt        Score      Error  Units
AllTypesHikari.inputStream  thrpt  200   399640.979 ± 3857.965  ops/s
MenuHikari.inputStream      thrpt  200  1132193.236 ± 9094.238  ops/s


After

AllTypesHikari.inputStream  thrpt  200   427716.513 ± 2677.172  ops/s
MenuHikari.inputStream      thrpt  200  1203096.246 ± 8188.514  ops/s
```

**Pull request merged**
